/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_tag_cmd                        19
#define gattdb_cmd_enter_deep_sleep           21
#define gattdb_cmd_ota_control                23
#define gattdb_cmd_beacon_rate_setting        25
#define gattdb_cmd_tag_features_control       27
#define gattdb_ota                            28
#define gattdb_ota_control                    30


#endif // __GATT_DB_H
